server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    uri: mongodb+srv://sa:R35rPvm0XFgR8dIh@walter.iyabt.mongodb.net/bootcamp?retryWrites=true&w=majority
management:
  endpoints:
    web:
      exposure:
        include: "*"